version: '3'
services:
    mongodb:
        image: mongodb
        ports:
            - "27017:27017"

    app:
        image: app
        ports:
            - "8080:8080"
        depends_on:
            - mongodb